### ISSUE TITLE
cannot load on fabric 1.18.2

### ISSUE THREAD

**Issue by szdytom** [ferriarnus/EnderBundle#6]
server crashes when player joins the game

```
[Server] java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[Server]        at com.ferri.arnus.enderbundle.crafting.Dyeing.method_8110(Dyeing.java:50) ~[enderbundle-
fabric-1.10.0.jar:?]
[Server]        at com.ferri.arnus.enderbundle.crafting.Dyeing$Serializer.toNetwork(Dyeing.java:119) ~[en
derbundle-fabric-1.10.0.jar:?]
[Server]        at com.ferri.arnus.enderbundle.crafting.Dyeing$Serializer.method_8124(Dyeing.java:61) ~[e
nderbundle-fabric-1.10.0.jar:?]
[Server]        at net.minecraft.class_2788.method_17816(class_2788.java:52) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2540.method_34062(class_2540.java:131) ~[server-intermediary.jar:?
]
[Server]        at net.minecraft.class_2788.method_11052(class_2788.java:27) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
[Server]        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[net
ty-all-4.1.68.Final.jar:?]
[Server]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerCont
ext.java:717) ~[netty-all-4.1.68.Final.jar:?]
[Server]        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHand
lerContext.java:764) ~[netty-all-4.1.68.Final.jar:?]
[Server]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.jav
a:790) ~[netty-all-4.1.68.Final.jar:?]
[Server]        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerCon
text.java:758) ~[netty-all-4.1.68.Final.jar:?]
[Server]        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHan...
```

**Comment by ferriarnus** [comment]
I think this issue will be resolved in the next release
